### ISSUE TITLE
Bin: Exit with non-zero when a "problem" is detected

### ISSUE THREAD

**Issue by papandreou** [Munter/hyperlink#1]
Use cases: CI, `git bisect run`

Could be configured by something like `checkLanguageKeys --stoponwarning --warn <messageType>,... --ignore <messageType>,...`.

https://github.com/assetgraph/assetgraph-builder/blob/master/bin/checkLanguageKeys#L15-L27

**Comment by Munter** [comment]
This is implemented in `v2.0.0`
