### ISSUE TITLE
Resolve directories to `index.html`

### ISSUE THREAD

**Issue by bebraw** [Munter/hyperlink#104]
Say I have reference like `<p><a href="writers-guide">Writer&#39;s guide</a></p>`. That should try out `writers-guide/index.html` in addition to `writers-guide.html` as a fallback.

**Comment by Munter** [comment]
I just checked hyperlink against webpack.js.org develop branch. The errors it's showing are real.

`<a href="writers-guide">Writer&#39;s guide</a>` should be `<a href="/writers-guide">Writer&#39;s guide</a>`

Same thing with the other error you saw. Missing a leading slash to make the url root relative
