### ISSUE TITLE
Allow checking anchors

### ISSUE THREAD

**Issue by bebraw** [Munter/hyperlink#105]
Let's say I have `<p><a href="writers-guide#foo">Writer&#39;s guide</a></p>`. It would be handy to check that the anchors exist. 

To quote @Munter, `findRelations({ to: { type: 'Html' }, href: /#/}).every(relation => return relation.to.parseTree.document.querySelector(relation.href.match(/#.*/)))` or so might do the trick.

**Comment by Munter** [comment]
Released in 2.5.0
