### ISSUE TITLE
Crashes against webpack.js.org

### ISSUE THREAD

**Issue by bebraw** [Munter/hyperlink#106]
I'm getting

```bash
.../webpack.js.org/node_modules/hyperlink/lib/index.js:193
        if (error.message.indexOf('AssetGraph.ensureAssetConfigHasType: Couldn\'t load') === 0) {
                         ^

TypeError: Cannot read property 'indexOf' of undefined
```

if running against [webpack.js.org](https://github.com/webpack/webpack.js.org). Hash: da4a57f29512b9b645431cbb7854b82a1ecb7ad0 .

The strange thing is that [Travis doesn't crash](https://travis-ci.org/webpack/webpack.js.org/builds/169196676), but it's on a newer Node (v6.5.0 vs. v6.9.1). I tried a fresh `npm install`, but it's still the same.

The link errors are something for me to fix. Just thought to point out this potential crash. For a reason I don't understand `error.message` can be `undefined` and adding a check like `if (error.message && error.message...` fixes the problem.

**Comment by Munter** [comment]
I need to write done tests :(

**Comment by bebraw** [comment]
I think it had something to do with my Node version since Travis gave proper errors. I've fixed them since. But yeah, let's leave this open. 👍

**Comment by Munter** [comment]
No, there are proper errors in there. I'm diving into it now. Might have uncovered some paths in assetgraph that usually don't get exercised

**Comment by Munter** [comment]
Fixed in 2.6.0

Also found 6 new errors in your code base with it :)

**Comment by bebraw** [comment]
Just updated. Getting

```bash
Error: Cannot find module './assetNodeOffsetDescription'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../webpack.js.org/node_modules/hyperlink/lib/index.js:7:34)
```

for some reason (tried with fresh install of hyperlink too). It might be missing some file based on the error.

**Comment by bebraw** [comment]
It's definitely missing `./assetNodeOffsetDescription` from the released version (tried a standalone project). The problem has to do with [files](https://github.com/Munter/hyperlink/blob/master/package.json#L31). Change `lib/index.js` to `lib` to fix.

**Comment by Munter** [comment]
Oh dear. Too restrictive package.json `files` :(

**Comment by Munter** [comment]
Fixed in 2.6.1

**Comment by bebraw** [comment]
Thanks! Works great.

**Comment by Munter** [comment]
Actually the errors you are getting about not being allowed to have digits first in an id are wrong. Jut did some research on it. I'll update the hyperlink behavior to not report that as an error

**Comment by bebraw** [comment]
Alright. Fixed anyway. 👍
