### ISSUE TITLE
No compatible version found: assetgraph@'>=1.17.5 <2.0.0'

### ISSUE THREAD

**Issue by cmckni3** [Munter/hyperlink#11]
Getting this error when trying to install.

**Comment by cmckni3** [comment]
The problem is that assetgraph specifies a node version below 0.12 and I am running 0.12.2.

**Comment by Munter** [comment]
Assetgraph is currently not node 0.12 compatible, so the engine version range is restricted. We're trying to figure out how to deal with the breaking changes in jsdom to get back up to date

**Comment by Munter** [comment]
Released in 2.2.0

**Comment by cmckni3** [comment]
Excellent :+1:
