### ISSUE TITLE
iconv issue?

### ISSUE THREAD

**Issue by hemanth** [Munter/hyperlink#13]
```sh
$ hyperlink http://h3manth.com/new
TAP version 13
# Crawling internal assets
ok 1 loading http://h3manth.com/new
not ok 2 should not have any errors loading asset
  ---
    operator: error
    expected:
      
    actual:
      "node-iconv not found. Cannot decode [Html/1 http://h3manth.com/new] (encoding is iso-8859-1). Please run `npm install iconv` and try again"
    at: http://h3manth.com/new
  ...

1..2
# tests 2
# pass  1
# fail  1
```

Same results even after `npm install iconv` am I missing something here?

**Comment by Munter** [comment]
I must be honest and say I don't remember what the story is with node-iconv. @papandreou you usually remember these things, can you explain what's happening? It's just assetgraph behind the scenes

**Comment by papandreou** [comment]
Yes, assetgraph will detect `iconv` in parent `node_modules` folders (using a try...catched `require`) and use it when encountering a charset not supported natively by node.js.

I can reproduce the error with h3manth.com, but it does work if I install iconv. Maybe you have `hyperlink` installed globally? In that case you need to run `npm install -g iconv`. I don't know if we can detect that case and output the correct command.

**Comment by hemanth** [comment]
@papandreou Thanks, it worked.
