### ISSUE TITLE
False negatives

### ISSUE THREAD

**Issue by Znarkus** [Munter/hyperlink#182]
Running hyperlink with `-p -v -r  dist/index.html` and getting false negatives like this:

```
not ok 21 load dist/set-designer-1
```

Which is strange since `set-designer-1` is never referenced in any of the files in `dist/`.
Any idea what's going on?
I could send the dist/ folder if it would help, or if you could give me some pointers where I should start to debug :)

**Comment by papandreou** [comment]
Can you share the contents of your `dist` folder? Then we can take a look.

**Comment by Znarkus** [comment]
Sure! https://www.dropbox.com/s/agf159wdyuitgtv/dist.zip?dl=0

**Comment by Munter** [comment]
First intuition is were not handling the difference between links that end in slashes and non-slashes to the same asset very well

**Comment by papandreou** [comment]
Yeah, it happens in https://github.com/Munter/hyperlink/blob/d07ea7caa8337bb68aa73221fac979435cfc4d10/lib/index.js#L485 when the target asset has already been visited. I've implemented a fix here: https://github.com/Munter/hyperlink/pull/183
