### ISSUE TITLE
Security vulnerability in deprecated package

### ISSUE THREAD

**Issue by ccsaposs** [Munter/hyperlink#185]
Hi,

This package depends on optimist, which [is deprecated](https://github.com/substack/node-optimist#readme) and uses an outdated version of minimist, which [is vulnerable](https://www.npmjs.com/advisories/1179).

Would it be possible to replace this dependency?

Thank you for your time.

**Comment by papandreou** [comment]
Sure, replaced with yargs in 4.5.3 🤗

**Comment by ccsaposs** [comment]
Thank you!
