### ISSUE TITLE
Can I mark a file/node to be ignored?

### ISSUE THREAD

**Issue by jameshfisher** [Munter/hyperlink#187]
Here's an example page that causes an error, `Parse error in inline JavaScript in test_case.html\nUnknown node type ChainExpression.`

```html
<!doctype html>
<html lang="en">
  <body>
    <script>
      foo = bar?.baz;
    </script>
  </body>
</html>
```

The error here is, I believe, because `hyperlink` doesn't know about [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). That's OK: I can't expect it to understand every bleeding-edge JS experiment.

But I do expect the freedom to use bleeding-edge browser features without this causing all CI to fail. I would like to be able to mark a file/node/section as "trust me, I know what I'm doing, don't test this", e.g. like this

```html
<!doctype html>
<html lang="en">
  <body>
    <script data-hyperlink-ignore>
      foo = bar?.baz;
    </script>
  </body>
</html>
```

Is this possible today? If so, could I see an example? Thanks!

**Comment by jameshfisher** [comment]
(A similar thing happened here https://github.com/Munter/netlify-plugin-checklinks/issues/286)

**Comment by papandreou** [comment]
Optional chaining is supported by the newest version of acorn, which assetgraph has adopted on master, but it hadn't been released yet. I've just backported it to 6.x and released 6.3.0.

If you update to the just released hyperlink 4.6.0, it should work :hugs:

**Comment by Munter** [comment]
In the selective ignore pattern, it would be possible to create some patterns, for example in HTML, which hyperlink could exclude. I just don't like the idea much. I can't think of a convention that would be generally applicable across all the asset types that we support, and I'm not a big fan of spreading a lot of build tool specifics into your code either.

And even if we came up with a convention for ignoring parts of your dependency graph, how can the tool then give you any guarantees anymore?

I think assetgraph (tool behind hyperlink) should always support code that can run in modern browsers. Of course than hinges on there being updated releases of the specific parsers we are depending on, and us having the time to upgrade them :)

**Comment by jameshfisher** [comment]
Awesome work, I'll try it out again :-)

What I was getting at, I suppose, is:

* My blog is always often experimental web stuff, because that's often what I blog about, and in general I'd expect build tools etc to be behind latest Chrome (obviously it's awesome if this is not the case ... call me a pessimist)
* I don't think of hyperlink as giving me any guarantees as such ... more of a useful heuristic tool. Like I guess it can't guarantee that `fetch('https://goo' + 'gle.com')` is "correct"
* Lots of testing/correctness tools have escape hatches, like `//@ts-ignore`, or `@ignore`

**Comment by papandreou** [comment]
`// @hyperlink-ignore` /  `<!-- hyperlink-ignore -->` could be an interesting idea :heart_eyes:

**Comment by jameshfisher** [comment]
Tried it out, `hyperlink@4.6.0` works like a charm, 1229 tests passed 💖

I've removed all my old `{% post_url %}` and `{% link %}` checks from Jekyll days.

Thanks again for an awesome tool!
