### ISSUE TITLE
Spurious fail caused by `fetch("https://some.url.that/only/accepts/post", { method: "POST" })`

### ISSUE THREAD

**Issue by jameshfisher** [Munter/hyperlink#188]
## Steps to reproduce

```html
<!doctype html>
<html>
  <script>
    fetch("https://some.url.that/only/accepts/post", { method: "POST" });
  </script>
</html>
```

## Expected behavior

All tests pass, because no requests made by this page will result in a 404.

## Actual behavior

```
not ok 2 load https://some.url.that/only/accepts/post
  ---
    operator: load
    expected: "200 https://some.url.that/only/accepts/post"
    actual:   "getaddrinfo ENOTFOUND some.url.that"
    at: _site/test_case.html:4:12 (inlined JavaScript)
```

It seems that when `hyperlink` finds `fetch("somestringliteral", { ... })`, it will try to `GET somestringliteral`, and fail if it gets a 404.

## Workaround

I can currently outsmart `hyperlink` by writing

```html
<!doctype html>
<html>
  <script>
    const theUrl = "https://some.url.that/only/accepts/post";
    fetch(theUrl, { method: "POST" });
  </script>
</html>
```

But this is undesirable, because I have to obfuscate my code to get around the testing tool.

## Desired change

* Option 1: `hyperlink` should only follow a `fetch()` URL if it knows for sure that it's a GET request (although I think this is going down a deep rabbithole)
* Option 2: some kind of escape hatch like https://github.com/Munter/hyperlink/issues/187

**Comment by Munter** [comment]
Fetch had always been difficult to reason about for assetgraph. There's are cases where it's used to fetch internal static assets, which would make sense to check, and in assetgraphs other user cases to include in the build. But this case is obviously wrong behavior, and hyperlink also shouldn't attempt other http methods either.

I'm inclined to say that hyperlink should maybe just assume fetch is not used for static content by default, and not check the link at all.

It maybe it should only follow fetch requests if the URL had a known static file extension.

@papandreou what do you think?

**Comment by papandreou** [comment]
I think we should stop modelling `fetch` And let users opt in with `fetch(‘/foo.json’.toString(‘url’))`.
