### ISSUE TITLE
img src ignores ``--internal``

### ISSUE THREAD

**Issue by danielfdickinson** [Munter/hyperlink#198]
I've got another one for you... 👾 

* ``<img src="https://github.com/danielfdickinson/image-handling-mod-hugo-dfd/actions/workflows/build-and-verify.yml/badge.svg" alt="build-and-verify">`` (which is currently 404 because that workflow hasn't run yet) in an HTML file
* Using an ``index.html`` as the entry point (instead my usual of a sitemap)
* command-line: ``hyperlink --canonicalroot https://example.com/ --internal -r -p public/index.html``

The following error is thrown:

```text
not ok 131 load https://github.com/danielfdickinson/image-handling-mod-hugo-dfd/actions/workflows/build-and-verify.yml/badge.svg
  ---
    operator: load
    expected:
      "200 https://github.com/danielfdickinson/image-handling-mod-hugo-dfd/actions/workflows/build-and-verify.yml/badge.svg"
    actual:
      "HTTP 404 Not Found"
    at: public/docs/readme/index.html:48:11 <img src="https://github.com/danielfdickinson/image-handling-mod-hugo-dfd/actions/workflows/build-and-verify.yml/badge.svg" alt="build-and-verify">
  ...
```
Might need the same thing as #181 but for images (?).

**Comment by papandreou** [comment]
Thanks for the report! Fixed in 5.0.4
